language: python
python:
  - 3.3
  - 3.4
install:
  - pip install coverage
  - pip install python-coveralls
  - python setup.py install
script:
  - nosetests --with-coverage --cover-package=web
after_success:
  - coveralls
